import type { Customer, Opportunity, Task, User, Team, Contact } from "./types";

export const INITIAL_USERS: User[] = [
  { id: "u1", fullName: "Nguyễn Văn Quân", email: "quan.nguyen@hctech.vn", role: "admin", teamId: null, isActive: true, pendingApproval: false, avatarInitials: "QN", createdAt: "2024-01-10" },
  { id: "u2", fullName: "Trần Thị Hương", email: "huong.tran@hctech.vn", role: "team_lead", teamId: "t1", isActive: true, pendingApproval: false, avatarInitials: "HT", createdAt: "2024-01-12" },
  { id: "u3", fullName: "Lê Quốc Anh", email: "anh.le@hctech.vn", role: "team_lead", teamId: "t2", isActive: true, pendingApproval: false, avatarInitials: "AL", createdAt: "2024-01-12" },
  { id: "u4", fullName: "Phạm Văn Hùng", email: "hung.pham@hctech.vn", role: "sales_staff", teamId: "t1", isActive: true, pendingApproval: false, avatarInitials: "HP", createdAt: "2024-01-15" },
  { id: "u5", fullName: "Hoàng Thị Mai", email: "mai.hoang@hctech.vn", role: "sales_staff", teamId: "t1", isActive: true, pendingApproval: false, avatarInitials: "MH", createdAt: "2024-01-15" },
  { id: "u6", fullName: "Vũ Minh Tuấn", email: "tuan.vu@hctech.vn", role: "sales_staff", teamId: "t2", isActive: true, pendingApproval: false, avatarInitials: "TV", createdAt: "2024-02-01" },
  { id: "u7", fullName: "Đặng Thị Lan", email: "lan.dang@hctech.vn", role: "sales_staff", teamId: "t2", isActive: true, pendingApproval: false, avatarInitials: "LD", createdAt: "2024-02-01" },
  { id: "u8", fullName: "Bùi Văn Nam", email: "nam.bui@hctech.vn", role: "sales_staff", teamId: null, isActive: false, pendingApproval: true, avatarInitials: "NB", createdAt: "2024-05-10" },
  { id: "u9", fullName: "Lý Thị Ngọc", email: "ngoc.ly@hctech.vn", role: "sales_staff", teamId: null, isActive: false, pendingApproval: true, avatarInitials: "NL", createdAt: "2024-05-14" },
];

export const INITIAL_TEAMS: Team[] = [
  { id: "t1", name: "Nhóm KD Miền Nam", leadId: "u2", region: "Miền Nam", memberIds: ["u4", "u5"], createdAt: "2024-01-12" },
  { id: "t2", name: "Nhóm KD Miền Bắc", leadId: "u3", region: "Miền Bắc", memberIds: ["u6", "u7"], createdAt: "2024-01-12" },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: "c1", name: "Nhà máy Dệt may Phương Đông", segment: "manufacturing", products: ["oil_ring", "dry"], phone: "028 3456 7890", email: "contact@phuongdong.com.vn", address: "KCN Tân Bình, TP.HCM", ownerId: "u4", teamId: "t1", status: "active", notes: "Khách hàng lâu năm, ưu tiên bơm công suất lớn.", createdAt: "2024-02-05" },
  { id: "c2", name: "Công ty CP Thực phẩm VISSAN", segment: "food_processing", products: ["water_ring", "maintenance"], phone: "028 3566 1234", email: "kinhdoanh@vissan.com.vn", address: "Quận Bình Thạnh, TP.HCM", ownerId: "u4", teamId: "t1", status: "active", notes: "Cần bơm đạt tiêu chuẩn vệ sinh thực phẩm.", createdAt: "2024-02-10" },
  { id: "c3", name: "Nhà máy Dược phẩm Imexpharm", segment: "pharmaceutical", products: ["dry", "oil_ring"], phone: "0292 381 6000", email: "info@imexpharm.com", address: "TP. Sa Đéc, Đồng Tháp", ownerId: "u5", teamId: "t1", status: "active", notes: "Yêu cầu bơm khô cho dây chuyền đóng gói thuốc.", createdAt: "2024-02-15" },
  { id: "c4", name: "Bệnh viện Chợ Rẫy", segment: "hospital", products: ["oil_ring", "repair"], phone: "028 3855 4137", email: "bvchory@choray.vn", address: "201B Nguyễn Chí Thanh, Q5, TP.HCM", ownerId: "u6", teamId: "t2", status: "active", notes: "Hợp đồng bảo trì thiết bị y tế hàng năm.", createdAt: "2024-03-01" },
  { id: "c5", name: "Phòng khám Đa khoa Columbia Asia", segment: "clinic", products: ["oil_ring"], phone: "028 3823 8888", email: "contact@columbia-asia.com", address: "8 Alexandre de Rhodes, Q1, TP.HCM", ownerId: "u6", teamId: "t2", status: "active", notes: "Trang bị mới hoàn toàn, ngân sách cao.", createdAt: "2024-03-05" },
  { id: "c6", name: "Công ty Cơ khí Viglacera", segment: "manufacturing", products: ["water_ring", "dry"], phone: "024 3777 0011", email: "viglacera@viglacera.com.vn", address: "KCN Tiên Sơn, Bắc Ninh", ownerId: "u7", teamId: "t2", status: "active", notes: "Đang mở rộng nhà máy phía Bắc.", createdAt: "2024-03-10" },
  { id: "c7", name: "Minh Phú Seafood Corp", segment: "food_processing", products: ["water_ring", "maintenance"], phone: "0297 381 0006", email: "mpseafood@minhphu.com.vn", address: "KCN Khánh An, Cà Mau", ownerId: "u5", teamId: "t1", status: "active", notes: "Xuất khẩu thủy sản, cần bơm hoạt động liên tục 24/7.", createdAt: "2024-03-12" },
  { id: "c8", name: "DHT Pharma Corporation", segment: "pharmaceutical", products: ["dry", "maintenance"], phone: "024 3514 6868", email: "info@dht.com.vn", address: "KCN Quang Minh, Hà Nội", ownerId: "u4", teamId: "t1", status: "active", notes: "Mua mới 3 bộ bơm cho nhà máy Bắc Ninh.", createdAt: "2024-03-20" },
  { id: "c9", name: "Bệnh viện Đa khoa Bình Dương", segment: "hospital", products: ["oil_ring"], phone: "0274 382 5888", email: "bvbd@bvbinhduong.vn", address: "274 Yersin, Bình Dương", ownerId: "u6", teamId: "t2", status: "active", notes: "Sắp đầu tư nâng cấp phòng phẫu thuật.", createdAt: "2024-04-02" },
  { id: "c10", name: "Phòng khám Nha khoa Dr. Smile", segment: "clinic", products: ["oil_ring", "repair"], phone: "028 3925 6789", email: "hello@drsmile.vn", address: "45 Trần Hưng Đạo, Q1, TP.HCM", ownerId: "u7", teamId: "t2", status: "active", notes: "Chuỗi 5 phòng khám, tập trung ở TP.HCM.", createdAt: "2024-04-08" },
  { id: "c11", name: "Nhựa Bình Minh", segment: "manufacturing", products: ["water_ring", "oil_ring"], phone: "028 3891 4199", email: "kinhdoanh@nhuabinhminh.com.vn", address: "KCN Bình Chiểu, TP.HCM", ownerId: "u4", teamId: "t1", status: "active", notes: "Nhà máy cũ, thiết bị hỏng hóc nhiều.", createdAt: "2024-04-10" },
  { id: "c12", name: "Đường Mía Ninh Hòa", segment: "food_processing", products: ["water_ring"], phone: "0258 388 3678", email: "ninhhoasugar@nhs.com.vn", address: "Ninh Hòa, Khánh Hòa", ownerId: "u5", teamId: "t1", status: "active", notes: "Mùa vụ tập trung tháng 12-4 hàng năm.", createdAt: "2024-04-15" },
  { id: "c13", name: "Dược phẩm OPC", segment: "pharmaceutical", products: ["oil_ring", "dry", "repair"], phone: "028 3855 0091", email: "opc@opc.com.vn", address: "1000 Trần Hưng Đạo, Q5, TP.HCM", ownerId: "u6", teamId: "t2", status: "active", notes: "Khách VIP, cần chăm sóc đặc biệt.", createdAt: "2024-04-20" },
  { id: "c14", name: "Bệnh viện FV", segment: "hospital", products: ["oil_ring", "maintenance"], phone: "028 3411 3333", email: "info@fvhospital.com", address: "6 Nguyễn Lương Bằng, Q7, TP.HCM", ownerId: "u7", teamId: "t2", status: "active", notes: "Bệnh viện quốc tế, tiêu chuẩn cao, trả chậm.", createdAt: "2024-05-01" },
  { id: "c15", name: "Saigon Beauty Clinic", segment: "clinic", products: ["oil_ring"], phone: "028 3990 1234", email: "booking@saigonbeauty.vn", address: "22 Lý Tự Trọng, Q1, TP.HCM", ownerId: "u4", teamId: "t1", status: "active", notes: "Mới khai trương, cần tư vấn kỹ.", createdAt: "2024-05-05" },
];

export const INITIAL_CONTACTS: Contact[] = [
  { id: "ct1", customerId: "c1", name: "Nguyễn Thành Đạt", title: "Trưởng phòng Kỹ thuật", phone: "0903 111 222", email: "dat.nguyen@phuongdong.com.vn", isPrimary: true },
  { id: "ct2", customerId: "c1", name: "Trần Văn Bình", title: "Giám đốc Sản xuất", phone: "0912 333 444", email: "binh.tran@phuongdong.com.vn", isPrimary: false },
  { id: "ct3", customerId: "c2", name: "Lê Thị Oanh", title: "Trưởng phòng Mua hàng", phone: "0906 555 666", email: "oanh.le@vissan.com.vn", isPrimary: true },
  { id: "ct4", customerId: "c3", name: "Phạm Quang Huy", title: "Giám đốc Kỹ thuật", phone: "0908 777 888", email: "huy.pham@imexpharm.com", isPrimary: true },
  { id: "ct5", customerId: "c4", name: "BS. Nguyễn Văn Cường", title: "Trưởng khoa Phẫu thuật", phone: "028 3855 4137", email: "cuong@choray.vn", isPrimary: true },
  { id: "ct6", customerId: "c5", name: "Ms. Jennifer Nguyen", title: "Facility Manager", phone: "0905 999 000", email: "jennifer.n@columbia-asia.com", isPrimary: true },
  { id: "ct7", customerId: "c6", name: "Hoàng Minh Khoa", title: "TP. Cơ điện", phone: "0967 112 233", email: "khoa.hoang@viglacera.com.vn", isPrimary: true },
  { id: "ct8", customerId: "c7", name: "Trần Ngọc Toàn", title: "Giám đốc Kỹ thuật", phone: "0986 334 455", email: "toan.tran@minhphu.com.vn", isPrimary: true },
  { id: "ct9", customerId: "c8", name: "Đặng Hải Long", title: "Trưởng phòng Thiết bị", phone: "0978 556 677", email: "long.dang@dht.com.vn", isPrimary: true },
  { id: "ct10", customerId: "c11", name: "Bùi Thanh Sơn", title: "Giám đốc Nhà máy", phone: "0933 778 899", email: "son.bui@nhuabinhminh.com.vn", isPrimary: true },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  { id: "o1", title: "Cung cấp 2 bộ bơm BVOH-150 cho xưởng dệt", customerId: "c1", customerName: "Nhà máy Dệt may Phương Đông", product: "oil_ring", value: 145000000, stage: "negotiation", probability: 75, ownerId: "u4", teamId: "t1", dueDate: "2024-06-30", notes: "Khách yêu cầu bảo hành 2 năm và đào tạo vận hành.", activities: [{ id: "a1", type: "meeting", content: "Họp tư vấn kỹ thuật tại nhà máy. KH hài lòng với thông số kỹ thuật.", userId: "u4", createdAt: "2024-05-20" }, { id: "a2", type: "call", content: "Gửi báo giá chi tiết. KH đang so sánh với nhà cung cấp khác.", userId: "u4", createdAt: "2024-05-22" }], createdAt: "2024-05-01" },
  { id: "o2", title: "Bảo dưỡng định kỳ Q2/2024 - VISSAN", customerId: "c2", customerName: "Công ty CP Thực phẩm VISSAN", product: "maintenance", value: 28000000, stage: "won", probability: 100, ownerId: "u4", teamId: "t1", dueDate: "2024-06-15", notes: "Hợp đồng bảo dưỡng định kỳ 2 lần/năm đã ký.", activities: [{ id: "a3", type: "task", content: "Ký hợp đồng bảo dưỡng Q2. Lịch thực hiện: 10-12/6.", userId: "u4", createdAt: "2024-05-28" }], createdAt: "2024-04-15" },
  { id: "o3", title: "Bơm khô BVKH-100 cho dây chuyền đóng gói", customerId: "c3", customerName: "Nhà máy Dược phẩm Imexpharm", product: "dry", value: 220000000, stage: "quote", probability: 50, ownerId: "u5", teamId: "t1", dueDate: "2024-07-15", notes: "Cần đạt tiêu chuẩn GMP. Khách đang chờ phê duyệt ngân sách.", activities: [{ id: "a4", type: "visit", content: "Khảo sát thực địa nhà máy tại Sa Đéc. Đo đạc vị trí lắp đặt.", userId: "u5", createdAt: "2024-05-15" }], createdAt: "2024-05-10" },
  { id: "o4", title: "Sửa chữa 1 bộ bơm vòng dầu hỏng - Chợ Rẫy", customerId: "c4", customerName: "Bệnh viện Chợ Rẫy", product: "repair", value: 18500000, stage: "won", probability: 100, ownerId: "u6", teamId: "t2", dueDate: "2024-06-10", notes: "Sửa chữa khẩn cấp, ưu tiên xử lý trong 3 ngày.", activities: [{ id: "a5", type: "call", content: "BV báo bơm phòng phẫu thuật hỏng đột xuất. Đã cử kỹ thuật viên xuống ngay.", userId: "u6", createdAt: "2024-06-01" }], createdAt: "2024-06-01" },
  { id: "o5", title: "Trang bị bơm mới cho phòng khám Columbia Asia", customerId: "c5", customerName: "Phòng khám Đa khoa Columbia Asia", product: "oil_ring", value: 85000000, stage: "survey", probability: 25, ownerId: "u6", teamId: "t2", dueDate: "2024-08-01", notes: "Phòng khám đang trong giai đoạn thiết kế nội thất.", activities: [{ id: "a6", type: "meeting", content: "Họp với Facility Manager. Trình bày catalog sản phẩm.", userId: "u6", createdAt: "2024-05-25" }], createdAt: "2024-05-20" },
  { id: "o6", title: "Cung cấp bơm vòng nước cho nhà máy Viglacera Bắc Ninh", customerId: "c6", customerName: "Công ty Cơ khí Viglacera", product: "water_ring", value: 310000000, stage: "approach", probability: 10, ownerId: "u7", teamId: "t2", dueDate: "2024-09-30", notes: "Dự án mở rộng nhà máy, đang trong giai đoạn lập kế hoạch.", activities: [], createdAt: "2024-05-28" },
  { id: "o7", title: "Hợp đồng bảo dưỡng 12 bơm - Minh Phú 2024", customerId: "c7", customerName: "Minh Phú Seafood Corp", product: "maintenance", value: 96000000, stage: "negotiation", probability: 75, ownerId: "u5", teamId: "t1", dueDate: "2024-07-01", notes: "Đang đàm phán điều khoản phản ứng khẩn cấp 24h.", activities: [{ id: "a7", type: "call", content: "KH đề nghị giảm 5% cho hợp đồng dài hạn 3 năm.", userId: "u5", createdAt: "2024-05-30" }], createdAt: "2024-04-20" },
  { id: "o8", title: "Bơm khô cho nhà máy DHT Pharma - Bắc Ninh", customerId: "c8", customerName: "DHT Pharma Corporation", product: "dry", value: 450000000, stage: "survey", probability: 25, ownerId: "u4", teamId: "t1", dueDate: "2024-08-30", notes: "Dự án lớn, cần phối hợp với team kỹ thuật trung tâm.", activities: [{ id: "a8", type: "visit", content: "Khảo sát kỹ thuật tại KCN Quang Minh. Gặp Trưởng phòng Thiết bị.", userId: "u4", createdAt: "2024-05-18" }], createdAt: "2024-05-15" },
  { id: "o9", title: "Bơm dầu BVOH-100 cho phòng phẫu thuật BV Bình Dương", customerId: "c9", customerName: "Bệnh viện Đa khoa Bình Dương", product: "oil_ring", value: 132000000, stage: "quote", probability: 50, ownerId: "u6", teamId: "t2", dueDate: "2024-07-20", notes: "Đã gửi báo giá. Chờ phê duyệt từ ban giám đốc BV.", activities: [{ id: "a9", type: "meeting", content: "Tư vấn kỹ thuật tại BV. Đề xuất giải pháp phù hợp phòng phẫu thuật.", userId: "u6", createdAt: "2024-05-22" }], createdAt: "2024-05-10" },
  { id: "o10", title: "Sửa chữa bơm khoa nha khoa - Dr. Smile", customerId: "c10", customerName: "Phòng khám Nha khoa Dr. Smile", product: "repair", value: 12500000, stage: "won", probability: 100, ownerId: "u7", teamId: "t2", dueDate: "2024-06-05", notes: "Đã hoàn thành sửa chữa. Khách hàng hài lòng.", activities: [{ id: "a10", type: "task", content: "KT hoàn thành sửa chữa 2 bơm. Bàn giao và kiểm tra nghiệm thu.", userId: "u7", createdAt: "2024-06-03" }], createdAt: "2024-05-25" },
  { id: "o11", title: "Thay thế 4 bơm cũ hỏng - Nhựa Bình Minh", customerId: "c11", customerName: "Nhựa Bình Minh", product: "water_ring", value: 180000000, stage: "approach", probability: 10, ownerId: "u4", teamId: "t1", dueDate: "2024-10-01", notes: "KH đang đánh giá các nhà cung cấp. Cần demo sản phẩm.", activities: [{ id: "a11", type: "call", content: "Liên hệ khởi đầu. GĐ nhà máy đồng ý gặp tư vấn.", userId: "u4", createdAt: "2024-05-28" }], createdAt: "2024-05-28" },
  { id: "o12", title: "Bơm vòng nước cho mùa vụ 2024 - Đường Ninh Hòa", customerId: "c12", customerName: "Đường Mía Ninh Hòa", product: "water_ring", value: 67000000, stage: "lost", probability: 0, ownerId: "u5", teamId: "t1", dueDate: "2024-05-01", notes: "KH chọn nhà cung cấp giá thấp hơn. Cần theo dõi lại vào mùa vụ 2025.", activities: [{ id: "a12", type: "call", content: "KH thông báo đã chọn nhà cung cấp khác do giá tốt hơn 15%.", userId: "u5", createdAt: "2024-04-28" }], createdAt: "2024-03-15" },
  { id: "o13", title: "Hệ thống bơm toàn diện cho dây chuyền OPC mới", customerId: "c13", customerName: "Dược phẩm OPC", product: "oil_ring", value: 580000000, stage: "negotiation", probability: 75, ownerId: "u6", teamId: "t2", dueDate: "2024-08-15", notes: "Dự án lớn nhất Q2. Cần phối hợp nhiều bộ sản phẩm khác nhau.", activities: [{ id: "a13", type: "meeting", content: "Họp thương thảo hợp đồng lần 2. KH muốn thêm điều khoản bảo trì.", userId: "u6", createdAt: "2024-05-29" }], createdAt: "2024-04-10" },
  { id: "o14", title: "Bảo dưỡng thiết bị y tế - BV FV 2024", customerId: "c14", customerName: "Bệnh viện FV", product: "maintenance", value: 145000000, stage: "quote", probability: 50, ownerId: "u7", teamId: "t2", dueDate: "2024-07-30", notes: "BV FV yêu cầu kỹ thuật viên có chứng chỉ quốc tế.", activities: [{ id: "a14", type: "email", content: "Gửi hồ sơ năng lực và bảng giá dịch vụ bảo dưỡng.", userId: "u7", createdAt: "2024-05-20" }], createdAt: "2024-05-15" },
  { id: "o15", title: "Bơm dầu cho phòng khám Saigon Beauty", customerId: "c15", customerName: "Saigon Beauty Clinic", product: "oil_ring", value: 42000000, stage: "approach", probability: 10, ownerId: "u4", teamId: "t1", dueDate: "2024-09-01", notes: "Phòng khám mới khai trương, cần tư vấn chi tiết.", activities: [{ id: "a15", type: "call", content: "Gọi điện chào hàng. Owner quan tâm, hẹn gặp tuần sau.", userId: "u4", createdAt: "2024-05-30" }], createdAt: "2024-05-30" },
];

export const INITIAL_TASKS: Task[] = [
  { id: "tk1", title: "Gọi điện xác nhận lịch khảo sát Imexpharm", type: "call", status: "pending", customerId: "c3", customerName: "Nhà máy Dược phẩm Imexpharm", opportunityId: "o3", opportunityTitle: "Bơm khô BVKH-100 cho dây chuyền đóng gói", assigneeId: "u5", dueDate: "2024-06-05", notes: "Liên hệ anh Huy để xác nhận ngày khảo sát chính thức.", createdAt: "2024-05-28" },
  { id: "tk2", title: "Gửi báo giá chính thức cho BV Bình Dương", type: "email", status: "done", customerId: "c9", customerName: "Bệnh viện Đa khoa Bình Dương", opportunityId: "o9", opportunityTitle: "Bơm dầu BVOH-100 cho phòng phẫu thuật BV Bình Dương", assigneeId: "u6", dueDate: "2024-05-25", notes: "Đã gửi kèm tài liệu kỹ thuật và điều khoản bảo hành.", createdAt: "2024-05-20" },
  { id: "tk3", title: "Họp đàm phán hợp đồng OPC lần 3", type: "meeting", status: "in_progress", customerId: "c13", customerName: "Dược phẩm OPC", opportunityId: "o13", opportunityTitle: "Hệ thống bơm toàn diện cho dây chuyền OPC mới", assigneeId: "u6", dueDate: "2024-06-08", notes: "Chuẩn bị phương án giảm giá tối đa 3%.", createdAt: "2024-05-30" },
  { id: "tk4", title: "Thăm khách hàng Minh Phú - cập nhật tiến độ", type: "visit", status: "pending", customerId: "c7", customerName: "Minh Phú Seafood Corp", opportunityId: "o7", opportunityTitle: "Hợp đồng bảo dưỡng 12 bơm - Minh Phú 2024", assigneeId: "u5", dueDate: "2024-06-10", notes: "Ghé thăm nhà máy Cà Mau. Kiểm tra tình trạng bơm hiện tại.", createdAt: "2024-05-28" },
  { id: "tk5", title: "Gửi hồ sơ năng lực cho Columbia Asia", type: "email", status: "done", customerId: "c5", customerName: "Phòng khám Đa khoa Columbia Asia", opportunityId: "o5", opportunityTitle: "Trang bị bơm mới cho phòng khám Columbia Asia", assigneeId: "u6", dueDate: "2024-05-28", notes: "Gửi catalog tiếng Anh và chứng chỉ CE.", createdAt: "2024-05-25" },
  { id: "tk6", title: "Liên hệ lại DHT Pharma sau kỳ nghỉ lễ", type: "call", status: "overdue", customerId: "c8", customerName: "DHT Pharma Corporation", opportunityId: "o8", opportunityTitle: "Bơm khô cho nhà máy DHT Pharma - Bắc Ninh", assigneeId: "u4", dueDate: "2024-05-15", notes: "Đã quá hạn. Cần liên hệ ngay.", createdAt: "2024-05-10" },
  { id: "tk7", title: "Demo sản phẩm tại Nhựa Bình Minh", type: "visit", status: "pending", customerId: "c11", customerName: "Nhựa Bình Minh", opportunityId: "o11", opportunityTitle: "Thay thế 4 bơm cũ hỏng - Nhựa Bình Minh", assigneeId: "u4", dueDate: "2024-06-15", notes: "Mang theo model BCVN-75 để demo tại chỗ.", createdAt: "2024-05-30" },
  { id: "tk8", title: "Theo dõi tiến độ thanh toán - VISSAN Q2", type: "task", status: "pending", customerId: "c2", customerName: "Công ty CP Thực phẩm VISSAN", opportunityId: "o2", opportunityTitle: "Bảo dưỡng định kỳ Q2/2024 - VISSAN", assigneeId: "u4", dueDate: "2024-06-20", notes: "Theo dõi công nợ hợp đồng bảo dưỡng.", createdAt: "2024-05-28" },
  { id: "tk9", title: "Soạn hợp đồng bảo trì BV FV 2024", type: "task", status: "in_progress", customerId: "c14", customerName: "Bệnh viện FV", opportunityId: "o14", opportunityTitle: "Bảo dưỡng thiết bị y tế - BV FV 2024", assigneeId: "u7", dueDate: "2024-06-12", notes: "Hợp đồng song ngữ Anh-Việt theo yêu cầu.", createdAt: "2024-05-29" },
  { id: "tk10", title: "Gọi điện chào hàng Saigon Beauty", type: "call", status: "overdue", customerId: "c15", customerName: "Saigon Beauty Clinic", opportunityId: "o15", opportunityTitle: "Bơm dầu cho phòng khám Saigon Beauty", assigneeId: "u4", dueDate: "2024-05-20", notes: "KH đã hẹn nhưng chưa liên lạc lại.", createdAt: "2024-05-18" },
  { id: "tk11", title: "Chuẩn bị tài liệu kỹ thuật bơm GMP cho Imexpharm", type: "task", status: "pending", customerId: "c3", customerName: "Nhà máy Dược phẩm Imexpharm", opportunityId: "o3", opportunityTitle: "Bơm khô BVKH-100 cho dây chuyền đóng gói", assigneeId: "u5", dueDate: "2024-06-20", notes: "Cần bản tiếng Việt có xác nhận của bộ phận kỹ thuật.", createdAt: "2024-06-01" },
  { id: "tk12", title: "Gặp mặt Giám đốc Viglacera Bắc Ninh", type: "meeting", status: "pending", customerId: "c6", customerName: "Công ty Cơ khí Viglacera", opportunityId: "o6", opportunityTitle: "Cung cấp bơm vòng nước cho nhà máy Viglacera Bắc Ninh", assigneeId: "u7", dueDate: "2024-06-25", notes: "Gặp trực tiếp để trình bày phương án tổng thể.", createdAt: "2024-06-01" },
  { id: "tk13", title: "Báo cáo tuần cho Ban giám đốc", type: "task", status: "done", customerId: null, customerName: null, opportunityId: null, opportunityTitle: null, assigneeId: "u2", dueDate: "2024-05-31", notes: "Báo cáo KPI nhóm Q2.", createdAt: "2024-05-28" },
  { id: "tk14", title: "Theo dõi hợp đồng sau bán hàng - Chợ Rẫy", type: "task", status: "done", customerId: "c4", customerName: "Bệnh viện Chợ Rẫy", opportunityId: "o4", opportunityTitle: "Sửa chữa 1 bộ bơm vòng dầu hỏng - Chợ Rẫy", assigneeId: "u6", dueDate: "2024-06-12", notes: "Kiểm tra bơm sau 1 tuần sử chữa.", createdAt: "2024-06-03" },
  { id: "tk15", title: "Liên hệ lại Đường Ninh Hòa - kế hoạch 2025", type: "call", status: "pending", customerId: "c12", customerName: "Đường Mía Ninh Hòa", opportunityId: null, opportunityTitle: null, assigneeId: "u5", dueDate: "2024-10-01", notes: "Đặt lịch nhắc nhở theo dõi lại vào tháng 10/2024.", createdAt: "2024-05-01" },
];
